Server:
  port:8080

Spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academy
    username: postgres
    password: Riccardo2001
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
      database-platform: org.hibernate-dialect.PostgresSQLDialect